"use client"
import { Inter,Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { UserCourseListContext } from "./_context/UserCourseListContext";
import { useState } from "react";

const inter = Outfit({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [userCourseList,setUserCourseList]=useState([]);

  return (
    <ClerkProvider>
    <UserCourseListContext.Provider value={{userCourseList,setUserCourseList}}>

    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </UserCourseListContext.Provider>
    </ClerkProvider>
  );
}
